Don't run testInteractions if vectorisation is disabled.

diff --git a/tests/testInteractions.sh.in b/tests/testInteractions.sh.in
--- a/tests/testInteractions.sh.in
+++ b/tests/testInteractions.sh.in
@@ -5,20 +5,24 @@ echo ""
 rm -f test_nonsym_density_serial.dat test_nonsym_density_vec.dat
 
 echo "Running ./testInteractions"
-./testInteractions
 
-if [ -e test_nonsym_density_serial.dat ]
+if ./testInteractions == 0
 then
-  if python @srcdir@/difffloat.py test_nonsym_density_serial.dat test_nonsym_density_vec.dat @srcdir@/tolerance_testInteractions.dat
+  echo "testInteractions is redundant when vectorisation is disabled"
+else
+  if [ -e test_nonsym_density_serial.dat ]
   then
-    echo "Accuracy test passed"
+    if python @srcdir@/difffloat.py test_nonsym_density_serial.dat test_nonsym_density_vec.dat @srcdir@/tolerance_testInteractions.dat
+    then
+      echo "Accuracy test passed"
+    else
+      echo "Accuracy test failed"
+      exit 1
+    fi
   else
-    echo "Accuracy test failed"
+    echo "Error Missing test output file"
     exit 1
   fi
-else
-  echo "Error Missing test output file"
-  exit 1
 fi
 
 echo "------------"
