Updated the scripts running the tests to actually crash if they fail at any iteration and not just on the last one. Code formatting. Do not compile the FFT functions if FFTW is not found.

diff --git a/tests/test27cells.sh.in b/tests/test27cells.sh.in
--- a/tests/test27cells.sh.in
+++ b/tests/test27cells.sh.in
@@ -3,18 +3,28 @@
 for v in {0..3}
 do
     echo ""
-
+	
     rm -f brute_force_27_standard.dat swift_dopair_27_standard.dat
 
+    echo "Running ./test27cells -n 6 -r 1 -d 0 -f standard -v $v -a 1e-4"
     ./test27cells -n 6 -r 1 -d 0 -f standard -v $v -a 1e-4
 
     if [ -e brute_force_27_standard.dat ]
     then
-	python @srcdir@/difffloat.py brute_force_27_standard.dat swift_dopair_27_standard.dat @srcdir@/tolerance_27_normal.dat 6
+	if python @srcdir@/difffloat.py brute_force_27_standard.dat swift_dopair_27_standard.dat @srcdir@/tolerance_27_normal.dat 6
+	then
+	    echo "Accuracy test passed"
+	else
+	    echo "Accuracy test failed"
+	    exit 1
+	fi
     else
+	echo "Error Missing test output file"
 	exit 1
     fi
 
+    echo "------------"
+    
 done
 
 exit $?
