make tests crash and fail if any line in script fails

diff --git a/tests/test27cellsStars.sh.in b/tests/test27cellsStars.sh.in
--- a/tests/test27cellsStars.sh.in
+++ b/tests/test27cellsStars.sh.in
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# crash if anything in this script fails
+set -e
+
 # List each test that should be run
 declare -a TEST_LIST=(test27cellsStars test27cellsStars_subset)
 
@@ -8,7 +11,7 @@ for TEST in "${TEST_LIST[@]}"
 do
   # Test for particles with the same smoothing length
     echo ""
-    
+
     rm -f star_brute_force_27_standard.dat swift_star_dopair_27_standard.dat
 
     echo "Running ./$TEST -n 6 -N 7 -r 1 -d 0 -f standard"
diff --git a/tests/test27cellsStarsPerturbed.sh.in b/tests/test27cellsStarsPerturbed.sh.in
--- a/tests/test27cellsStarsPerturbed.sh.in
+++ b/tests/test27cellsStarsPerturbed.sh.in
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# crash if anything in this script fails
+set -e
+
 # Test for particles with the same smoothing length
     echo ""
 
diff --git a/tests/testActivePair.sh.in b/tests/testActivePair.sh.in
--- a/tests/testActivePair.sh.in
+++ b/tests/testActivePair.sh.in
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# crash if anything in this script fails
+set -e
+
 echo ""
 
 rm -f brute_force_pair_active.dat swift_dopair_active.dat
diff --git a/tests/testInteractions.sh.in b/tests/testInteractions.sh.in
--- a/tests/testInteractions.sh.in
+++ b/tests/testInteractions.sh.in
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# crash if anything in this script fails
+set -e
+
 echo ""
 
 rm -f test_nonsym_density_serial.dat test_nonsym_density_1_vec.dat test_nonsym_density_2_vec.dat test_nonsym_force_1_vec.dat test_nonsym_force_2_vec.dat
diff --git a/tests/testSelectOutput.sh.in b/tests/testSelectOutput.sh.in
--- a/tests/testSelectOutput.sh.in
+++ b/tests/testSelectOutput.sh.in
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# crash if anything in this script fails
+set -e
+
 echo "Creating initial conditions"
 python3 @srcdir@/makeInput.py
 
